In [41]:
%load_ext autoreload
#To update the imported files

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:
%autoreload
import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
import xgboost as xgb
from sklearn.metrics import mean_absolute_error
from sklearn.base import clone
from utilities_xgBoost import *

%matplotlib inline

pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)

In [43]:
selected_features = ["date_forecast", "direct_rad:W", "clear_sky_rad:W" , "diffuse_rad:W","is_in_shadow:idx", "relative_humidity_1000hPa:p"]

In [44]:
#load y values
y_a = pd.read_parquet('../Data_and_task/A/train_targets.parquet')
y_b = pd.read_parquet('../Data_and_task/B/train_targets.parquet')
y_c = pd.read_parquet('../Data_and_task/C/train_targets.parquet')
y_b = y_b.dropna()
y_c=y_c.dropna()

In [45]:
#Loading estimated/forecasted training_weather from file
X_estimated_a = pd.read_parquet('../Data_and_task/A/X_train_estimated.parquet')
X_estimated_b = pd.read_parquet('../Data_and_task/B/X_train_estimated.parquet')
X_estimated_c = pd.read_parquet('../Data_and_task/C/X_train_estimated.parquet')

#Loading observed weather from file
X_observed_a = pd.read_parquet('../Data_and_task/A/X_train_observed.parquet')
X_observed_b = pd.read_parquet('../Data_and_task/B/X_train_observed.parquet')
X_observed_c = pd.read_parquet('../Data_and_task/C/X_train_observed.parquet')

#Loading estimated/forecasted test_weather from file
X_test_a = pd.read_parquet('../Data_and_task/A/X_test_estimated.parquet')
X_test_b = pd.read_parquet('../Data_and_task/B/X_test_estimated.parquet')
X_test_c = pd.read_parquet('../Data_and_task/C/X_test_estimated.parquet')

In [46]:
xgBoost_a = xgBoost(X_observed_a, X_estimated_a, y_a, selected_features)
xgBoost_a.fit()
xgBoost_a.pred()

xgBoost_b = xgBoost(X_observed_b, X_estimated_b, y_b, selected_features)
xgBoost_b.fit()
xgBoost_b.pred()

xgBoost_c = xgBoost(X_observed_c, X_estimated_c, y_c, selected_features)
xgBoost_c.fit()
xgBoost_c.pred()


In [47]:
#Evaluate mean asbolute error
mae_a = xgBoost_a.mae()
print("A: Mean Absolute Error:", mae_a)

mae_b =xgBoost_b.mae()
print("B: Mean Absolute Error:", mae_b)

mae_c = xgBoost_c.mae()
print("C: Mean Absolute Error:", mae_c)

#Saving y_pred in a proper csv file
#filename = "CSV/second_submission.csv"
#submission(filename, y_pred)

A: Mean Absolute Error: 271.50978408702275
B: Mean Absolute Error: 45.25430121435226
C: Mean Absolute Error: 49.398893013268584


In [48]:
xgBoost_a.pred(X_test_a)

xgBoost_b.pred(X_test_b)

xgBoost_c.pred(X_test_c)


[[-0.6670817  -1.111886   -1.081068    1.912505    0.613693  ]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.58469915]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.46711427]
 ...
 [-0.6670817  -1.1077288  -1.064515    1.912505    0.470336  ]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.7087274 ]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.78926516]]
[[-0.6670847  -1.1118907  -1.0810686   1.9090255   0.6124732 ]
 [-0.6670847  -1.1118907  -1.0810686   1.9090255   0.5834794 ]
 [-0.6670847  -1.1118907  -1.0810686   1.9090255   0.46750328]
 ...
 [-0.6670847  -1.1077335  -1.0645152   1.9090255   0.46428156]
 [-0.6670847  -1.1118907  -1.0810686   1.9090255   0.7026768 ]
 [-0.6670847  -1.1118907  -1.0810686   1.9090255   0.78643686]]
[[-0.6631393  -1.1112114  -1.0805107   1.7000666   0.6291268 ]
 [-0.6631393  -1.1112114  -1.0805107   1.7000666   0.5656663 ]
 [-0.6631393  -1.1112114  -1.0805107   1.7000666   0.40066963]
 ...
 [-0.6631393  -1.1072206  -1.0645202  

In [49]:
y_pred_xgBoost = np.concatenate([xgBoost_a.pred, xgBoost_b.pred, xgBoost_c.pred], axis = 0)
print(y_pred_xgBoost)
filename = "CSV/sub.csv"
submission(filename, y_pred_xgBoost)

[13.548817 13.548817 13.548817 ...  0.        0.        0.      ]
