In [17]:
%load_ext autoreload
#To update the imported files

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [18]:
%autoreload
import os
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report, accuracy_score
from sklearn.metrics import mean_absolute_error
import seaborn as sns
%matplotlib inline

pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)

In [38]:
%cd -
%cd "C:/Users/Gustav/Documents/maskinlaering/ML_prosject/TDT4173-ML-task/src/Linear_Regression"
%run Linear_regression.ipynb
lin_pred = y_pred_linear_regression
print(lin_pred)
%cd -
%cd "C:/Users/Gustav/Documents/maskinlaering/ML_prosject/TDT4173-ML-task/src/XG_Boost"
%run XGBoost.ipynb
xg_pred = y_pred_xgBoost
print(xg_pred)

C:\Users\Gustav\Documents\maskinlaering\ML_prosject\TDT4173-ML-task\src\Linear_Regression
C:\Users\Gustav\Documents\maskinlaering\ML_prosject\TDT4173-ML-task\src\Linear_Regression
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
A: Mean Absolute Error: 290.8027368366438
B: Mean Absolute Error: 45.47061924626252
C: Mean Absolute Error: 51.524004739398606
[[-0.6670817  -1.111886   -1.081068    1.912505    0.613693  ]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.58469915]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.46711427]
 ...
 [-0.6670817  -1.1077288  -1.064515    1.912505    0.470336  ]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.7087274 ]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.78926516]]
[[-0.6670847  -1.1118907  -1.0810686   1.9090255   0.6124732 ]
 [-0.6670847  -1.1118907  -1.0810686   1.9090255   0.5834794 ]
 [-0.6670847  -1.1118907  -1.0810686   1.9090255   0.46750328]
 ...
 [-0.6670847  -1.1077335  -

C:\Users\Gustav\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Gustav\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Gustav\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


A: Mean Absolute Error: 271.50978408702275
B: Mean Absolute Error: 45.25430121435226
C: Mean Absolute Error: 49.398893013268584
[[-0.6670817  -1.111886   -1.081068    1.912505    0.613693  ]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.58469915]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.46711427]
 ...
 [-0.6670817  -1.1077288  -1.064515    1.912505    0.470336  ]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.7087274 ]
 [-0.6670817  -1.111886   -1.081068    1.912505    0.78926516]]
[[-0.6670847  -1.1118907  -1.0810686   1.9090255   0.6124732 ]
 [-0.6670847  -1.1118907  -1.0810686   1.9090255   0.5834794 ]
 [-0.6670847  -1.1118907  -1.0810686   1.9090255   0.46750328]
 ...
 [-0.6670847  -1.1077335  -1.0645152   1.9090255   0.46428156]
 [-0.6670847  -1.1118907  -1.0810686   1.9090255   0.7026768 ]
 [-0.6670847  -1.1118907  -1.0810686   1.9090255   0.78643686]]
[[-0.6631393  -1.1112114  -1.0805107   1.7000666   0.6291268 ]
 [-0.6631393  -1.1112114  -1.0805107   1.

In [45]:
meta_model = LinearRegression()
#den må fittes
meta_model.fit()

TypeError: LinearRegression.fit() missing 2 required positional arguments: 'X' and 'y'

In [47]:
X_new_meta = np.column_stack((lin_pred, xg_pred))

y_new_pred = y_pred_linear_regression.predict(X_new_meta)


AttributeError: 'Lin_reg' object has no attribute 'predict'